console.log(Math.round(4.6));
console.log(Math.round(4.5));
console.log(Math.ceil(4.1));
console.log(Math.ceil(4.2));
console.log(Math.ceil(4.5));
console.log(Math.ceil(4.9));
console.log(Math.floor(4.1));
console.log(Math.floor(4.2));
console.log(Math.floor(4.5));
console.log(Math.floor(-4.9));
console.log(Math.trunc(4.9));
console.log(Math.trunc(4.7));
console.log(Math.trunc(4.4));
console.log(Math.trunc(-4.2));
console.log(Math.sign(-4));
console.log(Math.sign(0));
console.log(Math.sign(4));
///////////////////////////////////
console.log(Math.pow(8,2));
console.log(Math.sqrt(64));
console.log(Math.abs(-4,7.2));
////////////////////////////////////////////////
console.log(Math.sin(90*Math.PI/180));
console.log(Math.cos(0*Math.PI/180));
console.log(Math.min(0,3,1,21,3,4,5));
console.log(Math.max(2,34,4,35,54,65,56));